remove space and hello 9

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -42,9 +42,10 @@ jobs:
         run: |
           echo "Configuring GKE credentials for cluster access..."
           gcloud container clusters get-credentials hello-api-cluster \
-            -- zone us-central1-a \
-            -- project ${{ secrets.GCP_PROJECT_ID }} || echo "Failed to configure GKE credentials."
+            --zone us-central1-a \
+            --project ${{ secrets.GCP_PROJECT_ID }} || echo "Failed to configure GKE credentials."
           kubectl config current-context || echo "Failed to set Kubernetes context."
+  
   
       - name: Check gcloud auth configuration
         run: |
